# Copyright 2004-2010 OpenERP SA
# Copyright 2014 Angel Moya <angel.moya@domatix.com>
# Copyright 2015-2020 Tecnativa - Pedro M. Baeza
# Copyright 2016-2018 Carlos Dauden <carlos.dauden@tecnativa.com>
# Copyright 2016-2017 LasLabs Inc.
# Copyright 2018 ACSONE SA/NV
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).

from odoo import api, fields, models


class ContractAbstractContract(models.AbstractModel):
    _inherit = "contract.recurrency.basic.mixin"
    _name = "contract.abstract.contract"
    _description = "Abstract Recurring Contract"

    # These fields will not be synced to the contract
    NO_SYNC = ["name", "partner_id", "company_id"]

    name = fields.Char(required=True)
    # Needed for avoiding errors on several inherited behaviors
    partner_id = fields.Many2one(
        comodel_name="res.partner", string="Partner", index=True
    )
    pricelist_id = fields.Many2one(comodel_name="product.pricelist", string="Pricelist")
    contract_type = fields.Selection(
        selection=[("sale", "Customer"), ("purchase", "Supplier")],
        default="sale",
        index=True,
    )
    journal_id = fields.Many2one(
        comodel_name="account.journal",
        string="Journal",
        domain="[('type', '=', contract_type)," "('company_id', '=', company_id)]",
        compute="_compute_journal_id",
        store=True,
        readonly=False,
        index=True,
    )
    company_id = fields.Many2one(
        "res.company",
        string="Company",
        required=True,
        default=lambda self: self.env.company.id,
    )
    line_recurrence = fields.Boolean(
        string="Recurrence at line level?",
        help="Mark this check if you want to control recurrrence at line level instead"
             " of all together for the whole contract.",
    )
    generation_type = fields.Selection(
        selection=lambda self: self._selection_generation_type(),
        default=lambda self: self._default_generation_type(),
        help="Choose the document that will be automatically generated by cron.",
    )
    contract_value = fields.Float(string='Contract value', )
    total_achievement = fields.Float(string='Total achievement %', readonly=True,
                                     digits=(10, 10),
                                     compute="_compute_total_contract_achievement")
    total_invoice = fields.Float(string='Total Invoice', compute="_compute_total_invoice")
    total_remaining = fields.Float(string='Total Remaining', compute="_compute_total_remaining")
    total_paid = fields.Float(string='Total paid', compute="_compute_total_paid")


    @api.model
    def _selection_generation_type(self):
        return [("invoice", "Invoice")]

    @api.model
    def _default_generation_type(self):
        return "invoice"

    @api.onchange("contract_type")
    def _onchange_contract_type(self):
        if self.contract_type == "purchase":
            self.contract_line_ids.filtered("automatic_price").update(
                {"automatic_price": False}
            )

    @api.depends("contract_type", "company_id")
    def _compute_journal_id(self):
        AccountJournal = self.env["account.journal"]
        for contract in self:
            domain = [
                ("type", "=", contract.contract_type),
                ("company_id", "=", contract.company_id.id),
            ]
            journal = AccountJournal.search(domain, limit=1)
            if journal:
                contract.journal_id = journal.id

    def _compute_total_invoice(self):
        for rec in self:
            total = 0.0
            print('========== rec ===========')
            invoices = rec._get_related_invoices()
            if invoices:
                for inv in invoices:
                    if inv.state == 'posted':
                        total += inv.amount_total_signed
            rec.total_invoice = total

    @api.depends('contract_value')
    def _compute_total_remaining(self):
        # for rec in self:
        #     total = 0.0
        #     invoices = rec._get_related_invoices()
        #     if invoices:
        #         for inv in invoices:
        #             if inv.state == 'posted':
        #                 total += inv.amount_residual
        #     rec.total_remaining = total
        for rec in self:
            total = 0.0
            total += rec.contract_value - rec.total_invoice
            rec.total_remaining = total



    def _compute_receivable_amount(self):
        for rec in self:
            total = 0.0
            invoices = rec._get_related_invoices()
            if invoices:
                for inv in invoices:
                    if inv.state == 'posted':
                        total += inv.amount_residual
            rec.receivable_amount = total

    def _compute_total_paid(self):
        for rec in self:
            total = 0.0
            rec.total_paid = rec.total_invoice - rec.receivable_amount


    def _compute_total_contract_achievement(self):
        # for rec in self:
        #     total = 0.0
        #     if rec.total_paid and rec.contract_value:
        #         total = (rec.total_paid / rec.contract_value) * 100
        #     rec.total_achievement = total
        total = 0.0
        for rec in self:
            if rec.total_invoice and rec.contract_value:
                total = (rec.total_invoice / rec.contract_value) * 100
            else:
                total = 0.0

            rec.total_achievement = total

    @api.depends('end_date_extension_line')
    def _compute_new_end_date(self):
        lines = self.env['contract.extension.line'].sudo().search([('contract_id', '=', self.id)])
        print('============ lines ========', lines)
        for rec in self:
            if lines:
                print('=========== ENTER =====1234', lines[0].new_extension_date)
                rec.new_end_date = lines[0].new_extension_date
            else:
                rec.new_end_date = None

    def create_insurance_policy(self):
        print('=========== TEST ===============')
        insurance_policy_obj = self.env['insurance.policy'].sudo()
        val = {}
        for rec in self:
            if rec.partner_id:
                val['customer_id'] = rec.partner_id
            if rec.date_start:
                val['date_from'] = rec.date_start
            if rec.date_end:
                val['date_to'] = rec.date_end
            if rec.contract_value:
                val['amount'] = rec.contract_value
            if rec.code:
                rec['contract_no'] = rec.code
            val['contract_id'] = self.id
        print('=========== val ===========', val)
        if val:
            insurance_policy_obj.create(val)
